<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pl</string>
		<string>pm</string>
		<string>t</string>
		<string>psgi</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\bperl\b</string>
	<key>name</key>
	<string>Perl Extended</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\bstate\b</string>
			<key>name</key>
			<string>storage.modifier.perl.extended</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!-&gt;)\b(try|catch)\b</string>
			<key>name</key>
			<string>keyword.control.perl.extended</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pragma.perl.extended</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=use|no)\s+\b(lib|strict|warnings|feature|utf8|mro|constant|diagnostics|auto(use|die)|parent|overload|version|open|[\d\._"]+)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.pragma.perl.extended</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=use)\s+\b(base|encoding)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(say)\b</string>
			<key>name</key>
			<string>support.function.perl.extended</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(@|%|\$)[a-zA-Z0-9_]\b</string>
			<key>name</key>
			<string>variable.other.perl.extended</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?=s([^\s\w\[({&lt;]).*\1([egimosr]*)([\}\)\;\,]|\s+))</string>
			<key>comment</key>
			<string>string.regexp.replaceXXX</string>
			<key>end</key>
			<string>((([egimosr]*)))(?=([\}\)\;\,]|\s+|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.replace.perl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.perl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.regexp-option.perl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(s\s*)([^\s\w\[({&lt;])</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.perl</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.perl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\2)</string>
					<key>name</key>
					<string>string.regexp.replaceXXX.simple_delimiter.perl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.perl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.regexp.replaceXXX.format.single_quote.perl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\['\\]</string>
							<key>name</key>
							<string>constant.character.escape.perl.perl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([^\s\w\[({&lt;])</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.perl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1</string>
					<key>name</key>
					<string>string.regexp.replaceXXX.format.simple_delimiter.perl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?=(?&lt;!\\)s\s*([^\s\w\[({&lt;]))</string>
			<key>comment</key>
			<string>string.regexp.replace.extended</string>
			<key>end</key>
			<string>\2((([egimosr]*x[egimosr]*)))\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.replace.perl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.perl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.regexp-option.perl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(s)\s*(.)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.perl</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.perl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\2)</string>
					<key>name</key>
					<string>string.regexp.replace.extended.simple_delimiter.perl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.perl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'(?=[egimosr]*x[egimosr]*)\b</string>
					<key>name</key>
					<string>string.regexp.replace.extended.simple_delimiter.perl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(.)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.perl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1(?=[egimosr]*x[egimosr]*)\b</string>
					<key>name</key>
					<string>string.regexp.replace.extended.simple_delimiter.perl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.perl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.perl.extended</string>
	<key>uuid</key>
	<string>4876db41-622a-42d0-85fa-ea8be6fbe533</string>
</dict>
</plist>
