<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pl</string>
		<string>pm</string>
		<string>t</string>
		<string>psgi</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\bperl\b</string>
	<key>name</key>
	<string>Perl Extended</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.perl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstate\b</string>
			<key>name</key>
			<string>storage.modifier.perl.extended</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!-&gt;)\b(try|catch)\b</string>
			<key>name</key>
			<string>keyword.control.perl.extended</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pragma.perl.extended</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=use)\s+\b(lib|strict|warnings|feature|utf8|mro|constant|diagnostics|auto(use|die)|parent|overload|version|open|[\d\._"]+)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.pragma.perl.extended</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=use)\s+\b(base|encoding)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(say)\b</string>
			<key>name</key>
			<string>support.function.perl.extended</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(@|%|\$)[a-zA-Z0-9_]\b</string>
			<key>name</key>
			<string>variable.other.perl.extended</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.perl.extended</string>
	<key>uuid</key>
	<string>4876db41-622a-42d0-85fa-ea8be6fbe533</string>
</dict>
</plist>
