update
upgrade

tap sanemat/font || true
tap phinze/homebrew-cask || true

install brew-cask

#install
install android-ndk
install android-sdk
install ansible
install ant
install appledoc
install clisp
install coda-cli
install fontforge
install fontconfig
install git
install git-flow
install git-now
install imagemagick
install lv
install mobile-shell
install mogenerator
install nkf
install python
install python3
install ruby
install sqlite
install sshfs
install the_silver_searcher
install tig
install tree
install vim --override-system-vi --with-lua --with-perl --with-python3
install vimpager
install w3m
install weechat
install wget
install xctool
install zsh
install haskell-platform

install --powerline ricty
