(global-set-key (kbd "C-m") 'newline-and-indent)
(global-set-key (kbd "C-c l") 'toggle-truncate-lines)
(global-set-key (kbd "C-c C-c") 'other-window)
(global-set-key (kbd "<f6>") 'linum-mode)
(global-set-key (kbd "C-x C-r") 'helm-recentf)
(global-set-key (kbd "C-c h") 'helm-mini)
(global-set-key (kbd "C-c C-f") 'helm-ls-git-ls)
(global-set-key (kbd "C-c C-f") 'helm-git-project)
(global-set-key (kbd "<f7>") 'point-undo)
(global-set-key (kbd "<f8>") 'point-redo)
(global-set-key (kbd "C-.") 'undo-tree-redo)
(global-set-key (kbd "C-c e") 'helm-flymake)
(global-set-key (kbd "C-x b") 'my-helm)
(global-set-key (kbd "C-x C-b") 'my-helm)
(global-set-key (kbd "C-x C-r") 'helm-recentf)
;;行儀のよくないマイナーモードのために2つ設定しておく
(global-set-key (kbd "C-c C-g") 'magit-status)
(global-set-key (kbd "C-c g") 'magit-status)
;; sequential-command
(sequential-command-setup-keys)
