(setq default-input-method "MacOSX")
(mac-set-input-method-parameter "com.justsystems.inputmethod.atok25.Japanese" `title "漢")
(mac-set-input-method-parameter "com.justsystems.inputmethod.atok25.Japanese" `cursor-type 'box)
(mac-set-input-method-parameter "com.justsystems.inputmethod.atok25.Japanese" `cursor-color "magenta")
(mac-set-input-method-parameter "com.justsystems.inputmethod.atok26.Japanese" `title "漢")
(mac-set-input-method-parameter "com.justsystems.inputmethod.atok26.Japanese" `cursor-type 'box)
(mac-set-input-method-parameter "com.justsystems.inputmethod.atok26.Japanese" `cursor-color "magenta")
