####################################################################################################
#オプション
####################################################################################################

#Emacsモード
bindkey -e
# ディレクトリ移動
## cdで移動してもpushdと同じようにディレクトリスタックに追加する。
setopt auto_pushd
## カレントディレクトリ中に指定されたディレクトリが見つからなかった場合に
## 移動先を検索するリスト。
cdpath=(~)
## フック関数を入れる変数
typeset -ga chpwd_functions
typeset -ga precmd_functions
typeset -ga preexec_functions

## ヒストリファイルにコマンドラインだけではなく実行時刻と実行時間も保存する。
setopt extended_history
## 同じコマンドラインを連続で実行した場合はヒストリに登録しない。
setopt hist_ignore_dups
## スペースで始まるコマンドラインはヒストリに追加しない。
setopt hist_ignore_space
## すぐにヒストリファイルに追記する。
setopt inc_append_history
## zshプロセス間でヒストリを共有する。
setopt share_history
## C-sでのヒストリ検索が潰されてしまうため、出力停止・開始用にC-s/C-qを使わない。
setopt no_flow_control


# プロンプト
## PROMPT内で変数展開・コマンド置換・算術演算を実行する。
setopt prompt_subst
## PROMPT内で「%」文字から始まる置換機能を有効にする。
setopt prompt_percent
## コピペしやすいようにコマンド実行後は右プロンプトを消す。
setopt transient_rprompt


setopt extended_glob
setopt mark_dirs
setopt pushd_ignore_dups
setopt list_packed
#重複した履歴は登録しない
setopt hist_ignore_all_dups
#スペースから始まる履歴を登録しない
setopt hist_ignore_space
setopt hist_save_nodups
setopt correct
#勝手に/を消さない
setopt noautoremoveslash
setopt nolistbeep
setopt complete_aliases
#補完をメニューにする
setopt auto_menu
setopt list_types

autoload -U colors
colors
autoload -Uz compinit
compinit
autoload -Uz zmv

#大文字小文字を区別しない
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
#補完メニューを矢印やらTABやらで選択できるようにする
zstyle ':completion:*:default' menu select=1

#バージョン管理システムの状態をうまいこと表示してくれる関数
autoload -Uz vcs_info
#どうせgitとsvnしか使わないからそれだけ有効に
zstyle 'vcs_info:*' enable git svn
zstyle ':vcs_info:*' formats '%F{cyan}%s[%b]%f'
zstyle ':vcs_info:*' actionformats '%F{red}%s[%b|%a]%f'


#履歴
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000


#lsコマンドに色をつける
export CLICOLOR=true

source $DOTFILES/zsh/hook.zsh
source $DOTFILES/zsh/prompt.zsh

#perlbrew
[[ -s $HOME/perl5/perlbrew/etc/bashrc ]] && source $HOME/perl5/perlbrew/etc/bashrc
