# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git perl cpanm)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export LANG="ja_JP.UTF-8"
export LANGUAGE="ja_JP.utf8:ja_JP.UTF-8:en_US:en_GB:en"

export HISTFILE=$HOME/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000

link=`ls -l ~/.zshrc | sed -e "s/^l.*-> //"`
export DOTFILES=$(cd $(dirname $link);cd ../;pwd)

typeset -U path
path=(
/android-sdk/tools(N-/)
/android-sdk/platform-tools(N-/)
$DOTFILES/git/bin(N-/)
$HOME/.nodebrew/current/bin(N-/)
$HOME/bin(N-/)
$HOME/perl5/bin(N-/)
$HOME/local/bin(N-/)
/opt/local/bin(N-/)
/usr/local/bin(N-/)
$path
)

#EDITORの設定、自分で入れたvimがあればそれを使う
if test -e /usr/local/bin/vim
then
    export EDITOR=/usr/local/bin/vim
else
    export EDITOR=vim
fi

#perlbrew
[[ -s $HOME/perl5/perlbrew/etc/bashrc ]] && source $HOME/perl5/perlbrew/etc/bashrc


stty stop undef >& /dev/null
